# Generated by Django 4.0.4 on 2023-06-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='due',
            field=models.DateTimeField(null=True),
        ),
    ]
